### PR TITLE
Update to 20.08.2

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by tsdgeos** [comment]
@barthalion can i get write access here?

**Review by tsdgeos — APPROVED** [review]

**Comment by barthalion** [comment]
@tsdgeos Are you sure you already don't? KDE team has access to all `org.kde.*` repos and you are a member of it.

**Comment by barthalion** [comment]
Ah, just noticed not all are set to write access. I will fix that.

**Comment by barthalion** [comment]
And done, all set to write now.

**Pull request merged**
